#!/bin/bash

set -e

USER=`whoami`
PIDFILE="/var/run/xpilot-infinity-server/xpilot-infinity-server.pid"
LOGFIFO="/var/run/xpilot-infinity-server/xpilot-infinity-server.fifo"

if [ "$USER" = "xpilotinfinity" ]; then
  source /etc/default/xpilot-infinity-server
  test -f "$DEFAULTMAP" || exit 0

  OPTIONS=""
  echo $REPORTMETA |grep -iq no && OPTIONS="+reportMeta"
  OPT="-noquit $OPTIONS $OTHEROPTIONS -map $DEFAULTMAP"
  LOGGER="logger -p daemon.notice -t xpilot-infinity-server"

  rm -f $LOGFIFO ; mkfifo $LOGFIFO
  /usr/games/xpilot-infinity-server $OPT 2>&1 >$LOGFIFO &
  echo "$!" >$PIDFILE
  $LOGGER -f $LOGFIFO &
elif [ "$USER" = "root" ]; then
  echo "XPilot server should not be run as root."
  exit 1
else
  /usr/games/xpilot-infinity-server $*
fi
