#!/bin/sh

set -e

if [ "$1" = configure ]; then
    # Add an alternative for xpilot and xpilot-infinity
    # - we prefer xpilot-infinity-x11 over xpilot for 'xpilot' as it is a
    #   superset of xpilot functionality
    update-alternatives --install /usr/games/xpilot xpilot \
        /usr/games/xpilot-infinity-x11 20
    # - but only make x11 version "normal" priority for xpilot-infinity,
    #   as the SDL version is expected to be better when it is
    #   ready
    update-alternatives --install /usr/games/xpilot-infinity xpilot-infinity \
        /usr/games/xpilot-infinity-x11 10
fi

#DEBHELPER#
