#!/bin/sh

set -e

if [ "$1" = configure ]; then
    # Add an alternative for xpilot and xpilot-infinity
    # - we prefer xpilot-infinity-sdl over xpilot-infinity-x11 and original
    #   original xpilot for 'xpilot' as it is a superset of
    #   original xpilot functionality
    update-alternatives --install /usr/games/xpilot xpilot \
        /usr/games/xpilot-infinity-sdl 30
    # - we prefer the SDL Infinity version over the X11 Infinity version
    update-alternatives --install /usr/games/xpilot-infinity xpilot-infinity \
        /usr/games/xpilot-infinity-sdl 20
fi

#DEBHELPER#
